version: '3.8'

services:
  meetscribe:
    build: .
    container_name: meetscribe_bot
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    volumes:
      - ./notes:/usr/src/app/notes
